version: 2.1

jobs:
  build-and-scan:
    machine:
      docker_layer_caching: true  # Enables Docker caching for faster builds
    steps:
      # Step 1: Check out the code
      - checkout

      # Step 2: Authenticate with Docker
      - run:
          name: Authenticate with Docker
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 3: Pull Base Image
      - run:
          name: Pull Image
          command: docker pull ubuntu:latest

      # Step 4: Install Anchore CLI
      - run:
          name: Install Anchore CLI
          command: |
            curl -sSL https://github.com/anchore/cli/releases/download/v0.10.0/anchore-cli-linux | sudo tee /usr/local/bin/anchore-cli
            sudo chmod +x /usr/local/bin/anchore-cli

      # Step 5: Start Anchore Engine
      - run:
          name: Start Anchore Engine
          command: |
            docker pull docker.io/anchore/anchore-engine:latest
            docker run -d --name anchore-engine --network host \
              -e ANCHORE_CLI_USER=admin \
              -e ANCHORE_CLI_PASS=foobar \
              docker.io/anchore/anchore-engine:latest

      # Step 6: Wait for Anchore Engine to Initialize
      - run:
          name: Wait for Anchore Initialization
          command: sleep 60  # Allow enough time for Anchore Engine to start

      # Step 7: Add and Analyze Image
      - run:
          name: Scan Image with Anchore
          command: |
            anchore-cli image add ubuntu:latest
            anchore-cli image wait ubuntu:latest
            anchore-cli image scan ubuntu:latest --severity "high,critical"

      # Step 8: Scan Code for Vulnerabilities
      - run:
          name: Code Scanning with Trivy
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/scripts/install.sh | sh
            trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      # Step 9: License and Dependency Scanning with Snyk
      - run:
          name: Dependency and License Scanning - Snyk
          command: |
            curl -o- https://raw.githubusercontent.com/snyk/snyk-install/master/install.sh | bash
            snyk auth "$SNYK_AUTH_TOKEN"
            snyk test --all-projects --severity-threshold=high

workflows:
  version: 2
  build-and-scan-workflow:
    jobs:
      - build-and-scan
