version: 2.1

orbs:
  trivy-orb: fifteen5/trivy-orb@1.0.0

jobs:
  vulnerability-scan:
    machine:
      docker_layer_caching: true  # Enables Docker caching for faster builds
    steps:
      # Step 1: Check out the code (if applicable) - VA
      - checkout

      # Step 2: Authenticate with Docker (optional, for private images)
      - run:
          name: Authenticate with Docker
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 3: Perform Trivy scan with the orb
      - trivy-orb/scan:
          image-name: ubuntu:latest
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: table

      # Step 4: Perform a license scan with Trivy
      - trivy-orb/scan:
          image-name: alpine:3.15
          scanners: license
          severity: UNKNOWN,HIGH,CRITICAL
          format: table

workflows:
  version: 2
  scan-workflow:
    jobs:
      - vulnerability-scan
