version: 2.1

orbs:
  trivy-orb: fifteen5/trivy-orb@1.0.0

jobs:
  vulnerability-scan:
    machine:
      docker_layer_caching: true
    steps:
      # Step 1: Check out the code (if applicable)
      - checkout

      # Step 2: Authenticate with Docker (optional, for private images)
      - run:
          name: Authenticate with Docker
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 3: Scan an image with Trivy Orb
      - trivy-orb/scan:
          arguments: "--severity HIGH,CRITICAL --ignore-unfixed ubuntu:latest"

      # Step 4: License scan with Trivy Orb
      - trivy-orb/scan:
          arguments: "--scanners license --severity UNKNOWN,HIGH,CRITICAL alpine:3.15"

workflows:
  version: 2
  scan-workflow:
    jobs:
      - vulnerability-scan
