version: 2.1

jobs:
  build-and-scan:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Authenticate with Docker
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Pull Image
          command: docker pull ubuntu:latest



      # Step 1: Install Anchore for vulnerability scanning
      - run:
          name: Scan for Container Vulnerabilities - Anchore
          command: |
            docker pull anchore/scan-action
            docker run anchore/scan-action hello-world-nginx

workflows:
  version: 2
  build-and-scan-workflow:
    jobs:
      - build-and-scan