version: 2.1

orbs:
  trivy: fifteen5/trivy@1.0.0

jobs:
  vulnerability-scan:
    machine:
      docker_layer_caching: true  # Enables Docker caching for faster builds
    steps:
      # Step 1: Check out the code (if applicable)
      - checkout

      # Step 2: Authenticate with Docker (optional, for private images)
      - run:
          name: Authenticate with Docker
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 3: Pull the Docker image to scan
      - run:
          name: Pull Docker Image
          command: docker pull ubuntu:latest

      # Step 4: Install Trivy vulnerability scanner
      - run:
          name: Install Trivy
          command: |
            # Fetch the latest release of Trivy
            TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
            
            # Download Trivy binary for Linux
            wget -q https://github.com/aquasecurity/trivy/releases/download/${TRIVY_VERSION}/trivy_${TRIVY_VERSION#v}_Linux-64bit.tar.gz -O trivy.tar.gz
            
            # Extract and install
            tar -xzf trivy.tar.gz
            sudo mv trivy /usr/local/bin/trivy
            trivy --version  # Verify installation

      # Step 5: Run Trivy scan on the container
      - run:
          name: Perform Vulnerability Scan with Trivy
          command: |
            trivy image --exit-code 1 --severity HIGH,CRITICAL ubuntu:latest
            
      # Step 6: Run Trivy scan for licenses
      - run:
          name: Perform License Scan with Trivy
          command: |
            #trivy image --format table --list-all-packages --severity HIGH,CRITICAL ubuntu:latest
            trivy image --format table --scanners license --severity UNKNOWN,HIGH,CRITICAL alpine:3.15


      # Step 7: Cleanup Docker resources (optional)
      - run:
          name: Cleanup Docker
          command: docker system prune -f

workflows:
  version: 2
  scan-workflow:
    jobs:
      - vulnerability-scan
  use-trivy-orb:
    jobs:
      - trivy/scan:
          args: '--no-progress --exit-code 1 image busybox'
