version: 2.1

orbs:
  trivy-orb: fifteen5/trivy-orb@1.0.0

jobs:
  vulnerability-scan:
    machine:
      docker_layer_caching: true
    steps:
      # Step 1: Check out the code (if applicable)
      - checkout

      # Step 2: Perform a vulnerability scan using Trivy Orb
      - trivy-orb/scan:
          image: ubuntu:latest

      # Step 3: Perform a license scan using Trivy Orb
      - trivy-orb/scan:
          image: alpine:3.15
          scanners: license

workflows:
  version: 2
  scan-workflow:
    jobs:
      - vulnerability-scan
