version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t hello-world-nginx .
      - run:
          name: Push Docker Image
          command: docker push hello-world-nginx
