version: 2.1

jobs:
  build-and-scan:
    machine:
      docker_layer_caching: true  # Enables Docker caching for faster builds
    steps:
      # Step 1: Check out the code
      - checkout

      # Step 2: Authenticate with Docker
      - run:
          name: Authenticate with Docker
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 3: Pull Base Image
      - run:
          name: Pull Image
          command: docker pull ubuntu:latest

workflows:
  version: 2
  build-and-scan-workflow:
    jobs:
      - build-and-scan
