version: 2.1

jobs:
  vulnerability-scan:
    machine:
      docker_layer_caching: true  # Enables Docker caching for faster builds
    steps:
      # Step 1: Check out the code (if applicable)
      - checkout

      # Step 2: Authenticate with Docker (optional, for private images)
      - run:
          name: Authenticate with Docker
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 3: Pull the Docker image to scan
      - run:
          name: Pull Docker Image
          command: docker pull ubuntu:latest

      # Step 4: Install Trivy vulnerability scanner
      - run:
          name: Install Trivy
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/scripts/install.sh | sh

      # Step 5: Run Trivy scan on the container
      - run:
          name: Perform Vulnerability Scan with Trivy
          command: |
            trivy image --exit-code 1 --severity HIGH,CRITICAL ubuntu:latest

      # Step 6: Cleanup Docker resources (optional)
      - run:
          name: Cleanup Docker
          command: docker system prune -f

workflows:
  version: 2
  scan-workflow:
    jobs:
      - vulnerability-scan
