version: 2.1

jobs:
  build:
    docker:
      - image: circleci/docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t hello-world-nginx .
      - run:
          name: Test Container
          command: docker run -d -p 8080:80 hello-world-nginx
      - run:
          name: Check Service
          command: curl -f http://localhost:8080

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
