version: 2.1

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Authenticate with Docker
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Pull Image
          command: docker pull ubuntu:latest

jobs:
  scan:
    docker:
      - image: circleci/docker:latest
    steps:
      - checkout
      - run:
          name: Scan for Container Vulnerabilities
          command: |
            docker pull anchore/scan-action
            docker run anchore/scan-action hello-world-nginx

