version: 2.1

jobs:
  build-and-scan:
    machine:
      docker_layer_caching: true  # Enables Docker caching for faster builds
    steps:
      # Step 1: Check out the code
      - checkout

      # Step 2: Authenticate with Docker
      - run:
          name: Authenticate with Docker
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 3: Pull Base Image
      - run:
          name: Pull Image
          command: docker pull ubuntu:latest
          
  scan:
    docker:
      - image: anchore/engine-cli:latest
    steps:
      - run:
          name: Anchore Scan
          command: |
            export ANCHORE_CLI_USER='admin'
            export ANCHORE_CLI_PASS='foobar'       
            echo "Adding image to Anchore Engine"
            anchore-cli image add $ANCHORE_SCAN_IMAGE
            echo "Waiting for image analysis to complete"
            counter=0
            while (! (anchore-cli image get $ANCHORE_SCAN_IMAGE | grep 'Status: analyzed') ) ; do echo -n "." ; sleep 10 ; if  ; then echo " Timeout waiting for analysis" ; exit 1 ; fi ; counter=$(($counter+1)) ; done
            echo "Analysis complete"
            if  ; then anchore-cli evaluate check $ANCHORE_SCAN_IMAGE  ; fi

workflows:
  version: 2
  build-and-scan-workflow:
    jobs:
      - build-and-scan
      - scan
